/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData home = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData home_1 = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData home_2 = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData home_outline =
      const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData home_3 = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData home_4 = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData home_circled =
      const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData home_5 = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData person = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData moon_inv =
      const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData moon_1 = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData wb_sunny =
      const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData sun = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData sun_filled =
      const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData warehouse =
      const IconData(0xe840, fontFamily: _kFontFam);
  static const IconData female = const IconData(0xf182, fontFamily: _kFontFam);
  static const IconData male = const IconData(0xf183, fontFamily: _kFontFam);
  static const IconData moon = const IconData(0xf186, fontFamily: _kFontFam);
}
